update_basket:
  name: Update Basket
  description: Manually update the basket and delivery data from the provider.
  fields: {}

align_shopping_list:
  name: Align Shopping List
  description: Remove items from Home Assistant's To Do list that are present in the planned basket.
  fields: {}
